#!/usr/local/bin/perl
#Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
#By starting with 1 and 2, the first 10 terms will be:
#
#1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
#
#Find the sum of all the even-valued terms in the sequence which do not exceed four million.
my $sum = 0;
my $n = 0;
my $phi = (1+sqrt(5))/2;
while(1){
	$fib = ($phi**$n-(1-$phi)**$n)/sqrt(5);
	if($fib<4000000){
		$sum+=$fib;
	} else {
		last;
	}
	$n+=3;
}
print "$sum\n";